# Generated by Django 5.2.4 on 2025-08-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add new book'), ('can_change_book', 'can change existing book'), ('can_delete_book', 'can delete a book')]},
        ),
    ]
